/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ai/deviation-explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Deviation */
        post: operations["ai_deviation_ai_deviation_explanation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/env-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Env Scan */
        post: operations["ai_env_scan_ai_env_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Records */
        get: operations["ai_records_ai_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Record */
        get: operations["ai_record_ai_records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/records/{record_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Confirm */
        post: operations["ai_confirm_ai_records__record_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/records/{record_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Reject */
        post: operations["ai_reject_ai_records__record_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/revenue-proposal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Revenue Proposal */
        post: operations["ai_revenue_proposal_ai_revenue_proposal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assistant Ask */
        post: operations["assistant_ask_assistant_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest */
        get: operations["backtest_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brain/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brain Claims */
        get: operations["brain_claims_brain_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brain/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brain Claim Detail */
        get: operations["brain_claim_detail_brain_claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brain/claims/{claim_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brain Claim Impact */
        get: operations["brain_claim_impact_brain_claims__claim_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brain/effects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brain Effects */
        get: operations["brain_effects_brain_effects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brain/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Brain Reindex */
        post: operations["brain_reindex_brain_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brain/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Brain Sweep
         * @description PLATFORM.md §12.5/§12.6 (work package B4): the sweep, read-only. Deliberately takes no
         *     model from ``app.state.model_factory`` / ``resolve_model`` above - ``bridge.sweep.
         *     run_sweep`` resolves its own default via ``nvplan.ai.agents.resolve_model(None,
         *     provider=config.AI_BRAIN_WRITE_PROVIDER)``, the same offline-by-default path B2/B3 use, so
         *     this route can never go live just because a credential sits in ``.env`` (see that
         *     function's own docstring).
         */
        get: operations["brain_sweep_brain_sweep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brain/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brain Validate */
        get: operations["brain_validate_brain_validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bridge/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bridge Apply */
        post: operations["bridge_apply_bridge_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deviation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deviation */
        get: operations["deviation_deviation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deviation/backtest-year": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deviation Backtest Year */
        get: operations["deviation_backtest_year_deviation_backtest_year_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description Load actuals. Send the file as the raw request body (Content-Type text/csv or the xlsx
         *     type) or point ``path`` at a file; with neither, ``data/illustrative/actuals.csv`` is loaded.
         */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kpis/{scenario_kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kpis */
        get: operations["kpis_kpis__scenario_kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan Grid */
        get: operations["plan_grid_plan_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Run */
        post: operations["plan_run_plan_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan Scenarios */
        get: operations["plan_scenarios_plan_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements/{scenario_kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statements */
        get: operations["statements_statements__scenario_kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trace/plan-value/{plan_value_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace Pv */
        get: operations["trace_pv_trace_plan_value__plan_value_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trace/statement-line/{statement_line_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace Sl */
        get: operations["trace_sl_trace_statement_line__statement_line_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AiRecordDetailOut
         * @description One record incl. the per-model-call audit log (GET /ai/records/{id} only; the list stays light).
         */
        AiRecordDetailOut: {
            /**
             * Call Log
             * @description One entry per model call: the literal system prompt + messages sent, the response, approx tokens, and summarization / eviction / cleared-tool-result markers.
             */
            call_log?: {
                [key: string]: unknown;
            }[];
            /** Category Code */
            category_code: string | null;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Confirmed By */
            confirmed_by: string | null;
            /** Created At */
            created_at: string | null;
            /** Id */
            id: number;
            /** Model Version */
            model_version: string;
            /**
             * Note Ids
             * @description external notes written by this record (env scan)
             */
            note_ids?: number[];
            /** Prompt Text */
            prompt_text: string;
            /** Proposed Value */
            proposed_value: number | null;
            /** Rationale */
            rationale: string;
            /** Response Text */
            response_text: string;
            /** Scenario Id */
            scenario_id: number | null;
            /** Status */
            status: string;
            /**
             * Total Usage
             * @description Real provider token usage summed over every model call of the run (input/output/total plus cache_read/cache_creation when reported), recomputed from call_log by nvplan.ai.audit.total_usage. Empty mapping with the fake model (no usage metadata); null when no call log was persisted.
             */
            total_usage?: {
                [key: string]: number;
            } | null;
            /** Touchpoint */
            touchpoint: string;
            /** Year */
            year: number | null;
        };
        /** AiRecordOut */
        AiRecordOut: {
            /** Category Code */
            category_code: string | null;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Confirmed By */
            confirmed_by: string | null;
            /** Created At */
            created_at: string | null;
            /** Id */
            id: number;
            /** Model Version */
            model_version: string;
            /**
             * Note Ids
             * @description external notes written by this record (env scan)
             */
            note_ids?: number[];
            /** Prompt Text */
            prompt_text: string;
            /** Proposed Value */
            proposed_value: number | null;
            /** Rationale */
            rationale: string;
            /** Response Text */
            response_text: string;
            /** Scenario Id */
            scenario_id: number | null;
            /** Status */
            status: string;
            /** Touchpoint */
            touchpoint: string;
            /** Year */
            year: number | null;
        };
        /**
         * AssistantAskIn
         * @description ``POST /assistant/ask`` (UI.md Part 3).
         */
        AssistantAskIn: {
            /** Question */
            question: string;
            /**
             * Scenario Kind
             * @default base
             */
            scenario_kind: string;
        };
        /** BacktestOut */
        BacktestOut: {
            /** Fits */
            fits: {
                [key: string]: unknown;
            }[];
            /** Illustrative */
            illustrative: boolean;
            /** Markdown */
            markdown: string;
            /** N Cases */
            n_cases: number;
            /** Skipped */
            skipped: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary: {
                [key: string]: unknown;
            }[];
            /** Summary Default Path */
            summary_default_path: {
                [key: string]: unknown;
            }[];
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
        };
        /** BacktestYearOut */
        BacktestYearOut: {
            /** Fits */
            fits: {
                [key: string]: unknown;
            }[];
            /** Note */
            note: string;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Train Window */
            train_window: number[];
            /** Year */
            year: number;
        };
        /**
         * BrainReindexOut
         * @description Result of rebuilding the claim index from ``brain/``: every candidate markdown
         *     file is re-read and its row recomputed. Nothing is imported from outside the
         *     repository - the files are already the record, and this only refreshes the
         *     database's copy of them (PLATFORM.md §3). ``indexed`` counts files whose row was
         *     (re)written this run; ``skipped_unchanged`` counts files whose stored hash already
         *     matched and were left alone; ``rejected`` counts files a strict reindex refused to
         *     turn into a row at all.
         */
        BrainReindexOut: {
            /** Files Seen */
            files_seen: number;
            /** Findings */
            findings?: components["schemas"]["FindingOut"][];
            /**
             * Indexed
             * @description files whose row was (re)written this run
             */
            indexed: number;
            /**
             * Rejected
             * @description paths rejected under strict reindexing
             */
            rejected?: string[];
            /**
             * Skipped Unchanged
             * @description files already current in the index; not rewritten
             */
            skipped_unchanged: number;
        };
        /**
         * BrainSweepOut
         * @description The sweep (PLATFORM.md §12.5/§12.6, work package B4): what is stale or newly true across
         *     ``brain/``, read-only - nothing here has ever written a file or changed a claim's status (see
         *     ``bridge.sweep``'s own module docstring).
         */
        BrainSweepOut: {
            /** Computed Derivation Findings */
            computed_derivation_findings?: components["schemas"]["FindingOut"][];
            /** Reversal Verdicts */
            reversal_verdicts?: components["schemas"]["ReversalVerdictOut"][];
            /**
             * Structural Findings
             * @description unresolved_link / effect_not_wired, reused from brainkit.validate
             */
            structural_findings?: components["schemas"]["FindingOut"][];
            /** Supersession Findings */
            supersession_findings?: components["schemas"]["FindingOut"][];
        };
        /** BrainValidateOut */
        BrainValidateOut: {
            /** Clean */
            clean: boolean;
            /** Errors */
            errors?: components["schemas"]["FindingOut"][];
            /** Warnings */
            warnings?: components["schemas"]["FindingOut"][];
        };
        /** BridgeApplyIn */
        BridgeApplyIn: {
            /**
             * Created By
             * @default bridge
             */
            created_by: string;
            /**
             * Label Suffix
             * @default
             */
            label_suffix: string;
        };
        /** BridgeApplyOut */
        BridgeApplyOut: {
            /**
             * Applied
             * @description plan years affected by a decided effect
             */
            applied?: number[];
            /**
             * Message
             * @description set (with plan_run=None) when there was nothing decided to apply
             */
            message?: string | null;
            plan_run?: components["schemas"]["PlanRunOut"] | null;
            /**
             * Shadowed
             * @description claim ids superseded by a newer decision on the same year
             */
            shadowed?: number[];
        };
        /** ClaimDetailOut */
        ClaimDetailOut: {
            /** Date */
            date: string | null;
            effect?: components["schemas"]["EffectOut"] | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceOut"][];
            /** Has Effect */
            has_effect: boolean;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Links */
            links?: components["schemas"]["ClaimLinkOut"][];
            /** Path */
            path: string | null;
            /** Reversal Condition */
            reversal_condition?: string | null;
            /** Slug */
            slug: string;
            /** Status */
            status: string | null;
            /** Title */
            title: string | null;
        };
        /** ClaimLinkOut */
        ClaimLinkOut: {
            /** Other Slug */
            other_slug?: string | null;
            /** Relation */
            relation: string;
        };
        /** ClaimOut */
        ClaimOut: {
            /** Date */
            date: string | null;
            /** Has Effect */
            has_effect: boolean;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Path */
            path: string | null;
            /** Slug */
            slug: string;
            /** Status */
            status: string | null;
            /** Title */
            title: string | null;
        };
        /** ConfirmIn */
        ConfirmIn: {
            /** Confirmed By */
            confirmed_by: string;
        };
        /** ConfirmOut */
        ConfirmOut: {
            record: components["schemas"]["AiRecordOut"];
            run: components["schemas"]["PlanRunOut"] | null;
        };
        /** DecidedEffectOut */
        DecidedEffectOut: {
            /** Category Code */
            category_code: string;
            /** Claim Id */
            claim_id: number;
            /** Decided On */
            decided_on?: string | null;
            /** Decision Slug */
            decision_slug: string;
            /** Decision Title */
            decision_title: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
            /** Year */
            year: number;
        };
        /** DeviationExplanationIn */
        DeviationExplanationIn: {
            /**
             * Scenario Kind
             * @default base
             */
            scenario_kind: string;
            /** Year */
            year: number;
        };
        /** DeviationOut */
        DeviationOut: {
            /** Note */
            note: string;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Scenario Id */
            scenario_id: number;
            /** Scenario Kind */
            scenario_kind: string;
            /** Scenario Label */
            scenario_label: string;
            /** Years */
            years: number[];
        };
        /** EffectOut */
        EffectOut: {
            /** Category Code */
            category_code?: string | null;
            /** Unit */
            unit?: string | null;
            /** Value */
            value?: number | null;
            /** Year */
            year?: number | null;
        };
        /** EnvScanIn */
        EnvScanIn: {
            /** Positions Subset */
            positions_subset?: string[] | null;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Resolved */
            resolved: boolean;
            /** Section */
            section: string;
            /** Tag Kind */
            tag_kind: string;
            /** Tag Raw */
            tag_raw: string;
            /** Target Path */
            target_path?: string | null;
            /** Text */
            text: string;
        };
        /**
         * FindingOut
         * @description ``brainkit.validate.Finding``, serialised. ``path`` is relative to the repository
         *     root, never absolute (UI.md Part 1).
         */
        FindingOut: {
            /** Code */
            code: string;
            /** Line */
            line?: number | null;
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Severity */
            severity: string;
        };
        /** GridCell */
        GridCell: {
            /** Ai Record Id */
            ai_record_id?: number | null;
            /** Path */
            path: string;
            /** Plan Value Id */
            plan_value_id: number;
            /** Value */
            value: number;
        };
        /** GridRow */
        GridRow: {
            /** Category Code */
            category_code: string;
            /** Cells */
            cells: {
                [key: string]: components["schemas"]["GridCell"];
            };
            /** Is Component */
            is_component: boolean;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Db Url */
            db_url: string;
            /** Illustrative */
            illustrative: boolean;
            /** N Actuals */
            n_actuals: number;
            /** N Scenarios */
            n_scenarios: number;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** ImpactRowOut */
        ImpactRowOut: {
            /** Category Code */
            category_code: string;
            /**
             * Displaced Default
             * @description the default value this decision replaced, when the derivation recorded one
             */
            displaced_default?: number | null;
            /** Path */
            path: string;
            /** Plan Value Id */
            plan_value_id: number;
            /** Scenario Kind */
            scenario_kind: string;
            /** Value */
            value: number;
            /** Year */
            year: number;
        };
        /** IngestOut */
        IngestOut: {
            /** Illustrative */
            illustrative: boolean;
            /**
             * Notes Seeded
             * @default 0
             */
            notes_seeded: number;
            /** Rows */
            rows: number;
            /** Source */
            source: string;
            /** Source Label */
            source_label: string;
        };
        /** KpiGridOut */
        KpiGridOut: {
            /** Illustrative */
            illustrative: boolean;
            /** Kpis */
            kpis: components["schemas"]["KpiOut"][];
            /** Scenario Id */
            scenario_id: number;
            /** Scenario Kind */
            scenario_kind: string;
            /** Scenario Label */
            scenario_label: string;
            /** Years */
            years: number[];
        };
        /**
         * KpiOut
         * @description One KPI across the scenario's years, with everything needed to defend it.
         */
        KpiOut: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Direction */
            direction: string;
            /**
             * Formula
             * @description Rendered from the same fields nvplan.core.kpi.evaluate reads
             */
            formula: string;
            /** Inputs */
            inputs: string[];
            /** Name */
            name: string;
            /** Quadrant */
            quadrant: string;
            /**
             * Rests On Opening Position
             * @description True when this KPI draws on the balance sheet or cash flow while the plan's actuals are still labelled ILLUSTRATIVE, so the opening balance sheet those statements roll forward from is an assumption, not a measured position. The arithmetic is sound; the position underneath it is not yet real data.
             * @default false
             */
            rests_on_opening_position: boolean;
            thresholds?: components["schemas"]["KpiThresholdsOut"] | null;
            /** Unit */
            unit: string;
            /** Values */
            values: components["schemas"]["KpiValueOut"][];
        };
        /** KpiThresholdsOut */
        KpiThresholdsOut: {
            /** Good */
            good: number;
            /**
             * Source
             * @description Where the threshold came from -- assumptions say so
             */
            source: string;
            /** Warn */
            warn: number;
        };
        /** KpiValueOut */
        KpiValueOut: {
            /**
             * Status
             * @description green | amber | red | unknown -- never green without evidence
             */
            status: string;
            /**
             * Value
             * @description None where the KPI is undefined, e.g. divide by zero
             */
            value: number | null;
            /** Year */
            year: number;
        };
        /** ParameterRow */
        ParameterRow: {
            /** Alpha */
            alpha?: number | null;
            /** Beta */
            beta?: number | null;
            /** Calc Version */
            calc_version?: string | null;
            /** Category Code */
            category_code: string;
            /** Growth Rate */
            growth_rate?: number | null;
            /** Parameter Id */
            parameter_id?: number | null;
            /** R Squared */
            r_squared?: number | null;
            /** Valorization Rate */
            valorization_rate?: number | null;
            /** Window From */
            window_from?: number | null;
            /** Window To */
            window_to?: number | null;
        };
        /** PlanGridOut */
        PlanGridOut: {
            /** Created At */
            created_at: string | null;
            /** Created By */
            created_by: string;
            /** Illustrative */
            illustrative: boolean;
            /** Parameters */
            parameters: components["schemas"]["ParameterRow"][];
            /** Rows */
            rows: components["schemas"]["GridRow"][];
            /** Scenario Id */
            scenario_id: number;
            /** Scenario Kind */
            scenario_kind: string;
            /** Scenario Label */
            scenario_label: string;
            /**
             * Unit
             * @default k EUR
             */
            unit: string;
            /** Years */
            years: number[];
        };
        /** PlanRunIn */
        PlanRunIn: {
            /** Created By */
            created_by: string;
            /**
             * Label Suffix
             * @default
             */
            label_suffix: string;
        };
        /** PlanRunOut */
        PlanRunOut: {
            /** Created At */
            created_at: string | null;
            /** Label */
            label: string;
            /** N Derivations */
            n_derivations: number;
            /** N Plan Values */
            n_plan_values: number;
            /** N Statement Lines */
            n_statement_lines: number;
            /** Parameter Ids */
            parameter_ids: {
                [key: string]: number;
            };
            /** Scenario Ids */
            scenario_ids: {
                [key: string]: number;
            };
        };
        /** RejectIn */
        RejectIn: {
            /** Rejected By */
            rejected_by: string;
        };
        /** RevenueProposalIn */
        RevenueProposalIn: {
            /**
             * Scenario Kind
             * @default base
             */
            scenario_kind: string;
            /** Year */
            year: number;
        };
        /** RevenueProposalOut */
        RevenueProposalOut: {
            /** Default Value */
            default_value: number;
            record: components["schemas"]["AiRecordOut"];
        };
        /**
         * ReversalVerdictOut
         * @description ``bridge.sweep.ReversalVerdict``, serialised. ``tripped`` is ``true``/``false`` only for a
         *     mechanically evaluated condition (``mechanism`` is ``"r_squared"`` or ``"plan_value"``);
         *     ``null`` means advisory - the model may have looked at it (``detail``), but nothing decided
         *     whether it has tripped (PLATFORM.md §12.1/§12.5 - only a human does).
         */
        ReversalVerdictOut: {
            /** Claim Id */
            claim_id: number;
            /** Condition Text */
            condition_text: string;
            /** Decision Slug */
            decision_slug: string;
            /** Decision Title */
            decision_title: string;
            /** Detail */
            detail: string;
            /** Mechanism */
            mechanism: string;
            /** Tripped */
            tripped: boolean | null;
        };
        /** ScenarioOut */
        ScenarioOut: {
            /** Created At */
            created_at: string | null;
            /** Created By */
            created_by: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
        };
        /** StatementCell */
        StatementCell: {
            /** Mapping Ref */
            mapping_ref: string;
            /** Statement Line Id */
            statement_line_id: number;
            /** Value */
            value: number;
        };
        /** StatementGridOut */
        StatementGridOut: {
            /**
             * Consistency
             * @description BS balance / cash-tie problems; empty = clean
             */
            consistency?: string[];
            /** Illustrative */
            illustrative: boolean;
            /** Rows */
            rows: components["schemas"]["StatementRow"][];
            /** Scenario Id */
            scenario_id: number;
            /** Scenario Kind */
            scenario_kind: string;
            /** Scenario Label */
            scenario_label: string;
            /** Statement */
            statement: string;
            /**
             * Unit
             * @default k EUR
             */
            unit: string;
            /** Years */
            years: number[];
        };
        /** StatementRow */
        StatementRow: {
            /** Cells */
            cells: {
                [key: string]: components["schemas"]["StatementCell"];
            };
            /** Line Code */
            line_code: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ai_deviation_ai_deviation_explanation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviationExplanationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_env_scan_ai_env_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvScanIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_records_ai_records_get: {
        parameters: {
            query?: {
                touchpoint?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRecordOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_record_ai_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRecordDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_confirm_ai_records__record_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_reject_ai_records__record_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_revenue_proposal_ai_revenue_proposal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevenueProposalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevenueProposalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_ask_assistant_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantAskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_backtest_get: {
        parameters: {
            query?: {
                window_len?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brain_claims_brain_claims_get: {
        parameters: {
            query?: {
                kind?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brain_claim_detail_brain_claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brain_claim_impact_brain_claims__claim_id__impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brain_effects_brain_effects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecidedEffectOut"][];
                };
            };
        };
    };
    brain_reindex_brain_reindex_post: {
        parameters: {
            query?: {
                /** @description default: the repository's brain/ directory */
                brain_root?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainReindexOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brain_sweep_brain_sweep_get: {
        parameters: {
            query?: {
                /** @description default: the repository's brain/ directory */
                brain_root?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainSweepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brain_validate_brain_validate_get: {
        parameters: {
            query?: {
                /** @description default: the repository's brain/ directory */
                brain_root?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainValidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bridge_apply_bridge_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BridgeApplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeApplyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deviation_deviation_get: {
        parameters: {
            query?: {
                scenario_kind?: string;
                year?: number | null;
                scenario_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deviation_backtest_year_deviation_backtest_year_get: {
        parameters: {
            query: {
                /** @description a year with actuals, e.g. 2025 */
                year: number;
                window_len?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestYearOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: {
                /** @description Label for rows without one (required for uploads) */
                source_label?: string | null;
                /** @description Server-side CSV/XLSX path; default: the illustrative CSV */
                path?: string | null;
                /** @description Also seed the illustrative external notes (once) */
                with_notes?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kpis_kpis__scenario_kind__get: {
        parameters: {
            query?: {
                scenario_id?: number | null;
            };
            header?: never;
            path: {
                scenario_kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiGridOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_grid_plan_grid_get: {
        parameters: {
            query?: {
                scenario_kind?: string;
                scenario_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanGridOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_run_plan_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_scenarios_plan_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
    statements_statements__scenario_kind__get: {
        parameters: {
            query?: {
                statement?: string;
                scenario_id?: number | null;
            };
            header?: never;
            path: {
                scenario_kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementGridOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_pv_trace_plan_value__plan_value_id__get: {
        parameters: {
            query?: {
                format?: string;
                max_depth?: number;
            };
            header?: never;
            path: {
                plan_value_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_sl_trace_statement_line__statement_line_id__get: {
        parameters: {
            query?: {
                format?: string;
                max_depth?: number;
            };
            header?: never;
            path: {
                statement_line_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
